const home = getDataJs('home')
const bookmarks = getDataJs('bookmarks')
const create = getDataJs('create')
const profile = getDataJs('profile')
const homeBtnActive = getDataJs('homeBtnActive')
const homeBtn = getDataJs('homeBtn')
const bookmarksBtnActive = getDataJs('bookmarksBtnActive')
const bookmarksBtn = getDataJs('bookmarksBtn')
const createBtnActive = getDataJs('createBtnActive')
const createBtn = getDataJs('createBtn')
const profileBtnActive = getDataJs('profileBtnActive')
const profileBtn = getDataJs('profileBtn')
const homeContent = getDataJs('homeContent')
const bookmarksContent = getDataJs('bookmarksContent')
const createContent = getDataJs('createContent')
const profileContent = getDataJs('profileContent')
const bookmarkActive = getDataJs('bookmarkActive')
const bookmark = getDataJs('bookmark')
const showAnswerBtn = getDataJs('showAnswerBtn')
const showAnswer = getDataJs('showAnswer')
const clearInput = getDataJs('clearInput')
const form = getDataJs('form')

clearInput.addEventListener('click', () => {
  form.reset()
})

showAnswerBtn.addEventListener('click', () => {
  showAnswer.classList.toggle('d-none')
})

bookmarkActive.addEventListener('click', () => {
  bookmarkActive.classList.add('d-none')
})

bookmark.addEventListener('click', () => {
  bookmarkActive.classList.remove('d-none')
})

homeBtn.addEventListener('click', () => {
  home.classList.remove('d-none')
  bookmarks.classList.add('d-none')
  profile.classList.add('d-none')
  create.classList.add('d-none')
  homeContent.classList.remove('d-none')
  bookmarksContent.classList.add('d-none')
  createContent.classList.add('d-none')
  profileContent.classList.add('d-none')
  homeBtnActive.classList.remove('d-none')
  homeBtn.classList.add('d-none')
  bookmarksBtnActive.classList.add('d-none')
  bookmarksBtn.classList.remove('d-none')
  createBtnActive.classList.add('d-none')
  createBtn.classList.remove('d-none')
  profileBtnActive.classList.add('d-none')
  profileBtn.classList.remove('d-none')
})

bookmarksBtn.addEventListener('click', () => {
  home.classList.add('d-none')
  bookmarks.classList.remove('d-none')
  profile.classList.add('d-none')
  create.classList.add('d-none')
  homeContent.classList.add('d-none')
  bookmarksContent.classList.remove('d-none')
  createContent.classList.add('d-none')
  profileContent.classList.add('d-none')
  homeBtnActive.classList.add('d-none')
  homeBtn.classList.remove('d-none')
  bookmarksBtnActive.classList.remove('d-none')
  bookmarksBtn.classList.add('d-none')
  createBtnActive.classList.add('d-none')
  createBtn.classList.remove('d-none')
  profileBtnActive.classList.add('d-none')
  profileBtn.classList.remove('d-none')
})

createBtn.addEventListener('click', () => {
  home.classList.add('d-none')
  bookmarks.classList.add('d-none')
  profile.classList.add('d-none')
  create.classList.remove('d-none')
  homeContent.classList.add('d-none')
  bookmarksContent.classList.add('d-none')
  createContent.classList.remove('d-none')
  profileContent.classList.add('d-none')
  homeBtnActive.classList.add('d-none')
  homeBtn.classList.remove('d-none')
  bookmarksBtnActive.classList.add('d-none')
  bookmarksBtn.classList.remove('d-none')
  createBtnActive.classList.remove('d-none')
  createBtn.classList.add('d-none')
  profileBtnActive.classList.add('d-none')
  profileBtn.classList.remove('d-none')
})

profileBtn.addEventListener('click', () => {
  home.classList.add('d-none')
  bookmarks.classList.add('d-none')
  profile.classList.remove('d-none')
  create.classList.add('d-none')
  homeContent.classList.add('d-none')
  bookmarksContent.classList.add('d-none')
  createContent.classList.add('d-none')
  profileContent.classList.remove('d-none')
  homeBtnActive.classList.add('d-none')
  homeBtn.classList.remove('d-none')
  bookmarksBtnActive.classList.add('d-none')
  bookmarksBtn.classList.remove('d-none')
  createBtnActive.classList.add('d-none')
  createBtn.classList.remove('d-none')
  profileBtnActive.classList.remove('d-none')
  profileBtn.classList.add('d-none')
})

function getDataJs(name) {
  const selector = `[data-js=“${name}”]`
  return document.querySelector(selector)
}
